name: CI

on:
  push:
    branches:
      - '[0-9]*'
      - 'feat/**'
      - 'bugfix/**'

permissions:
  contents: write


jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run isort
        run: poetry run isort . --check --diff

      - name: Run black
        run: poetry run black . --check --diff

      - name: Run flake8
        run: poetry run flake8 .

      - name: Run pytest
        run: poetry run pytest  --cov=spoteamfy --cov-report=term-missing

  build-mkdocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Install MkDocs and theme
        run: poetry add mkdocs mkdocs-material

      - name: Build MkDocs site
        run: poetry run mkdocs gh-deploy

#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: mkdocs-site
#          path: site/
